### ISSUE TITLE
Smoothing on a linear network

### ISSUE THREAD

**Issue by agila5** [luukvdmeer/sfnetworks#11]
**Is your feature request related to a problem? Please describe.**
I know that this is a very difficult problem with no general solution and thousands of different approaches (see the references at the bottom of the issue), but I think we should code a few functions that implement basic smoothing approaches on a linear network. AFAIK the idea of smoothing spatial estimates for areal data is very common in epidemiology using bayesian methods (e.g. [here](https://journal.r-project.org/archive/2018/RJ-2018-036/RJ-2018-036.pdf), [here](https://cran.r-project.org/web/packages/SpatialEpiApp/vignettes/manual.pdf) and [here](https://cran.r-project.org/web/packages/diseasemapping/diseasemapping.pdf)). I will explore other R packages that already implemented this procedure for polygonal areas. 

**Describe the solution you'd like**
Given a fixed spatial network and corresponding measurements, return the same network data after smoothing the measurements. I'm not 100% sure that we can straightforwardly apply the same methods as for polygonal areas. 

**Describe alternatives you've considered**
For example this is the code to implement the simplest (and ugliest) spatial smoother. 

``` r
# create a very simple network
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
library(tmap)

network_column <- st_sfc(
  st_linestring(matrix(c(0, -2, 0, -1, 0, 0), ncol = 2, byrow = TRUE)), 
  st_linestring(matrix(c(0, 2, 0, 1, 0, 0), ncol = 2, byrow = TRUE)), 
  st_linestring(matrix(c(-2, 0, -1, 0, 0, 0), ncol = 2, byrow = TRUE)), 
  st_linestring(matrix(c(2, 0, 1, 0, 0, 0), ncol = 2, byrow = TRUE)), 
  st_linestring(matrix(c(2, -2, 2, -1, 2, 0), ncol = 2, byrow = TRUE)),
  st_linestring(matrix(c(2, 2, 2, 1, 2, 0), ncol = 2, byrow = TRUE)), 
  st_linestring(matrix(c(2, 0, 3, 0, 4, 0), ncol = 2, byrow = TRUE))
)

# assign some random measurements to all edges
set.seed(1)
network_data <- st_as_sf(
  data.frame(measurements = rpois(7, runif(7, 0, 4))), 
  geometry = network_column
)

tm_shape(network_data) + 
  tm_lines(col = "measurements", palette = "viridis", style = "cat")
#> Warning: Currect projection of shape network_data unknown. Long-lat (WGS84) is
#> assumed.
```

![](https://i.imgur.com/SJxnVXT.png)

``` r

# estimate neighborhoods matrix
network_neigh <- st_touches(network_data)

# each measure is smoothed using a weighted average between its value and the
# mean of the values in it's neighborhood:
# alpha * x_i + (1 - alpha) * mean(x_i)
# where the mean is estimated wrt to the neighboord of the ith observation and
# alpha is the mixing proportion. For simplicity I set alpha = 0.5. For
# examples:

neighborhood_means <- vapply(
  X = network_neigh, 
  FUN = function(x) mean(network_data[x, "measurements", drop = TRUE]), 
  FUN.VALUE = numeric(1)
)

network_data$smoothed_measurements <- 0.5 * network_data[["measurements"]] + 0.5 * neighborhood_means

tm_shape(network_data) + 
  tm_lines(col = "smoothed_measurements", palette = "viridis", style = "cont")
#> Warning: Currect projection of shape network_data unknown. Long-lat (WGS84) is
#> assumed.
```

![](https://i.imgur.com/cznesWZ.png)

<sup>Created on 2020-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm not saying that this is a valid spatial smoother (and it's not) but I think it should give the right idea of what I'm talking about. 

**References**

* Banerjee, S., Carlin, B. P., & Gelfand, A. E. (2014). Hierarchical modeling and analysis for spatial data. Chapman and Hall/CRC.
* Besag J, York J, Molli ́e A (1991). “Bayesian image restoration with applications in spatialstatistics (with discussion).”Annals of the Institute of Statistical Mathematics,43, 1–59
* Lawson AB (2009).Bayesian Disease Mapping: Hierarchical Modeling In Spatial Epidemiol-ogy. Chapman and Hall/CRC.

**Comment by luukvdmeer** [comment]
Can I assign this to you, @agila5 ?

**Comment by agila5** [comment]
I'm super interested in this but I cannot work on this at least for a couple of weeks. If you can wait I will create a PR as soon as possible

**Comment by luukvdmeer** [comment]
I don't think there is a high priority right now, so that is not a problem

**Comment by agila5** [comment]
Hi! I just checked some of my old issues and, even if I think that this is still a very interesting topic (at least for my research), I also think that it's way too general to be summarized in a couple of functions. For these reasons, IMO this is out of scope for `sfnetworks`. Feel free to reopen if you want to discuss something.
