### ISSUE TITLE
CRAN errors with spatstat 2.0-1

### ISSUE THREAD

**Issue by loreabad6** [luukvdmeer/sfnetworks#137]
**Describe the bug**
We got an e-mail from CRAN with our first errors!

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_sfnetworks.html>.
> 
> The errors come from spatstat 2.0-1
> 
> Please correct before 2021-03-28 to safely retain your package on CRAN.
> 
> The CRAN Team

It seems like we need to link to the new `spatstat` sub-packages specifically for the methods and examples implemented (?) We [noticed that `sf` might be dealing with the same issues](https://github.com/r-spatial/sf/commit/8fb16e899222241302bd27f7c6811457dbfc735d#diff-9cc358405149db607ff830a16f0b4b21f7366e3c99ec00d52800acebe21b231c) which might give some hints on how to solve this. @agila5 could you look into this?

**Reproducible example**
Check CRAN results.

**Expected behavior**
Success!

**Comment by luukvdmeer** [comment]
This is on CRAN now and fixed the errors, thanks!
