### ISSUE TITLE
CRAN errors with GEOS version

### ISSUE THREAD

**Issue by loreabad6** [luukvdmeer/sfnetworks#140]
**Describe the bug**
We also have a different error unrelated to spatstat for the solaris flavor. Seems to be due to incompatible GEOS versions that allow the use of `st_reverse()`. It fails in tests and vignettes.

**Reproducible example**
See the [end of the check log](https://cran.r-project.org/web/checks/check_results_sfnetworks.html). 
Apparently it is not so easy to test for solaris with r-hub since versions and packages attached differ. When I try the `check_on_solaris()` I get an error that `sf`, `lwgeom` and `units` are not available and the checks stop.

**Expected behavior**
Success!

We could call in an if statement where the st_reverse examples are only applicable with GEOS > 3.7.

**Comment by luukvdmeer** [comment]
This is on CRAN now and fixed the errors, thanks!
