### ISSUE TITLE
Print method for sfnetwork objects

### ISSUE THREAD

**Issue by loreabad6** [luukvdmeer/sfnetworks#16]
Currently the `print` method for an object of class `sfnetworks` does not exists, and hence it defaults to the `print` method of a `tbl_graph` object. 

I would suggest, to keep it simple the same structure for the new `print` method, with a header indicating the class `sfnetworks` for the object, and with the properties of an `sf` object. 

Check on any potential problems when creating the method regarding the [new sf version](https://r-spatial.github.io/sf/news/index.html), mainly for [PROJ issues](https://www.r-spatial.org/r/2020/03/17/wkt.html)

Check also how tbl_graph prints. At the top it includes a general overview, e.g.:

`A tbl_graph: 701 nodes and 851 edges`

But then it gets specific depending on what operation was performed:

`A directed multigraph with 14 components`
`A rooted forest with 3 trees`, after an st_filter that reduces the network
`An empty graph` when the result is 0 nodes and 0 edges

**Comment by loreabad6** [comment]
With 9bdde929bafb04fb88577c1f73246c6b030a356c there is now a commit on branch develop that created a print method for an `sfnetwork` object combining information from the `print.sf` method and `print.tbl_graph` method. Things that need to be checked:

- [ ] is using `capture.output()` good practice for `print` methods?
- [ ] bug: `pillar::style_subtle()` not recognized inside method.

**Comment by loreabad6** [comment]
Prin method now depends less on `capture.output`, it mimics the `tbl_graph` print method, adding information from `sf` to the summary section of nodes and edges.

**Comment by luukvdmeer** [comment]
Advanced print method with tidyverse flavour is implemented ;)
