### ISSUE TITLE
Ordering of vignettes on CRAN

### ISSUE THREAD

**Issue by edzer** [luukvdmeer/sfnetworks#162]
CRAN orders vignettes alphabetically on the file name. If you give filenames like `vignette1`, `vignette2` etc., they come out in order on the CRAN landing page. Or, `1_structure.Rmd`, `2_preprocess_and_clean`, etc.

**Comment by luukvdmeer** [comment]
Thanks @edzer for raising this and thanks @agila5 for implementing! It is now on master and will be updated in the coming CRAN release
