### ISSUE TITLE
Plot method for sfnetwork objects

### ISSUE THREAD

**Issue by loreabad6** [luukvdmeer/sfnetworks#17]
Currently a `plot` method for an object of class `sfnetworks` does not exists, and hence it defaults to the `plot` method of a `igraph` object.

Suggestion: create a `plot` method that shows edges and nodes at once, on `base` R. To handle geometry, explore options of plotting `GEOMETRY COLLECTIONS`. Consider the case where `edges` are not `sf` lines, how to handle that? Should they be converted to an `sf` object just for plotting?

A simple `plot` method would be useful to have a quick overview of how the network looks like. However, for any advanced plotting, the user can export `edges` and `nodes` as `sf` objects and use their preferred plotting package and settings. Or in another case, plotting methods specific for network analysis with `igraph` or `tidygraph` for example. This should be emphasized on the description of the `plot` method.

**Comment by luukvdmeer** [comment]
Simple plot method that shows the geometry of nodes and edges in one plot is implemented
