### ISSUE TITLE
Morphing of sfnetwork objects

### ISSUE THREAD

**Issue by luukvdmeer** [luukvdmeer/sfnetworks#19]
**Is your feature request related to a problem? Please describe.**
The `tidygraph` package uses 'morphing' to create temporary alternative representations of a graph. See [here](https://tidygraph.data-imaginist.com/reference/morph.html). (Warning: it takes some thought to understand how this exactly works, but after that it is useful). `sfnetworks` does not support morphing yet.

**Describe the solution you'd like**
Since morphing is an important part of `tidygraph`, especially when doing more complicated graph analysis, we should support this also. The `sfnetwork` class simply subclasses `tbl_graph`, so all of `tidygraphs` morphers should already work, but along the way, there will probably be the need to add dedicated spatial morphers. Or at least, to enable users to create their own spatial morphers if they need them.

A `morphed_tbl_graph` is a separate class in `tidygraph`. Therefore, we need a `morphed_sfnetwork` class as well, which subclasses the `morphed_tbl_graph`. 

One spatial morpher I can think of would be `to_spatially_explicit_edges()`. This will come in handy when working with an `sfnetwork` that has an edges table containing `from` and `to` columns referring to its source and target nodes, but no geometry column. Of course, implicitly, these edges are spatial, because they refer to nodes which are spatial points. An alternative representation of this graph could then be a `morphed_sfnetwork` where a geometry column is added to the edges (as a LINESTRING between the source and target nodes). This enables to calculate the length of the edges with `st_length()`, and to plot the edges on a map (see https://github.com/luukvdmeer/sfnetworks/issues/17).

**Describe alternatives you've considered**
Simply rely on tidygraphs morphing functions. However, as said, dedicated spatial morphers might be needed.

**Note**
Adding a `morphed_sfnetwork` class will probably also create the need to write extra methods for `sf` functions. See https://github.com/luukvdmeer/sfnetworks/issues/18.

**Comment by luukvdmeer** [comment]
Addition:

Tidygraphs `to_subgraph()` morpher filters subsets nodes or edges based on an expression. In `sfnetworks`, it should be possible to use geometric binary predicates (i.e. st_intersects, st_touches, ..) as expression in this morpher.

**Comment by luukvdmeer** [comment]
More possible morphers:

- Something like `to_coordinates()` that replaces the geometry column of the nodes with an X and Y column.
- Something like `to_alternative_geometry()` that replaces the geometries of either nodes or edges by applying a [geometric unary operation](https://r-spatial.github.io/sf/reference/geos_unary.html). I for example would be interested in computing the area of the voronoi polygon of each node, which then could be done by `network %>% morph(to_alternative_geometry(op = st_voronoi)) %>% mutate(area_of_influence = st_area(geom)) %>% unmorph()`.

**Comment by Robinlovelace** [comment]
These all sound like good ideas to me.

**Comment by luukvdmeer** [comment]
I moved this to milestone 2 since it goes into more advanced tidygraph functionality

**Comment by luukvdmeer** [comment]
This is implemented in the new release. See the `extensions` vignette.
