### ISSUE TITLE
Outdated HTML snippet in roxygen generated Rd files

### ISSUE THREAD

**Issue by luukvdmeer** [luukvdmeer/sfnetworks#221]
E-mail from CRAN:

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_sfnetworks.html>.
> 
> In particular, please see the "Found the following HTML validation
> problems" NOTEs in the "HTML version of manual" check for the r-devel
> debian checks results. 
> 
> R 4.2.0 switched to use HTML5 for documentation pages.  Now validation
> using HTML Tidy finds problems in the HTML generated from your Rd files
> of the form
> 
>   <big> element removed from HTML5
>   <center> element removed from HTML5
>   <img> attribute "align" not allowed for HTML5
>   <img> attribute "hspace" not allowed for HTML5
>   <img> attribute "width" has invalid value "120px"
>   <img> attribute "width" has invalid value "480px"
>   <img> attribute "width" has invalid value "50px"
>   <img> attribute "width" has invalid value "72px"
> 
> For the first four, please see
> <https://html.spec.whatwg.org/#obsolete-but-conforming-features> for
> info on these: in principle, all can be fixed by using style attributes,
> e.g.
> 
>   style='text-align: right;'
> 
> instead of align='right' etc., which will work for both the new and old
> ways of converting Rd to HTML.
> 
> For the second four, simply drop the px units: the HTML5 standard asks
> for a non-negative integer implied to be in CSS pixels.
> 
> Can you please fix as necessary?
> 
> Note that the problems are found in Rd files auto-generated with
> roxygen2: to fix it might suffice to re-generate these using the current
> CRAN version of roxygen2.
> 
> Please correct before 2022-09-01 to safely retain your package on CRAN.
> 
> Best,
> -k

**Comment by luukvdmeer** [comment]
It is actually not about vignettes, but about .Rd files generated by roxygen2. Especially the sfnetworks-package.Rd file, which shows our logo and uses 'align=right' in the HTML snippet. That is not supported anymore in HTML5, apparently. Should be an easy fix by updating roxygen2 and re-generate the Rd file.

**Comment by Robinlovelace** [comment]
At a glance this looks relevant, hope of use, if not of interest: https://github.com/DavisVaughan/extrachecks-html5

**Comment by luukvdmeer** [comment]
Thanks @Robinlovelace, for now updating roxygen2 worked for us, but if new issues occur we should probably run those checks
