### ISSUE TITLE
Functions to snap points to nodes or edges

### ISSUE THREAD

**Issue by luukvdmeer** [luukvdmeer/sfnetworks#25]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a function that takes a (set of) spatial point(s), either as `sf`, `sfc` or `sfg`, and snaps them to the nearest node or nearest edge. In that way you can provide any spatial point to a shortest path query, no matter if it lies exactly on the network or not.

**Describe the solution you'd like**
A function `st_snap_point_to_node` that replaces the geometry of the given point by the geometry of the nearest node, and a function `st_snap_point_to_edge` that replaces the geometry of the given point by the nearest point on the nearest edge. The first can simply use sf's `st_nearest_feature` (or [st_nearest_node](https://github.com/luukvdmeer/sfnetworks/issues/20) if we implement that), the latter can use sf's `st_nearest_points` to find the nearest point on the nearest edge.

Probably these functions will need a `tolerance` argument, like `st_snap` in sf.

**Comment by luukvdmeer** [comment]
See also how the `shp2graph` package handles this: https://www.mdpi.com/2220-9964/7/8/293/pdf

![Screenshot from 2020-04-15 11-36-30](https://user-images.githubusercontent.com/26540305/79322966-ddc1f600-7f0d-11ea-99c3-08c4d5a14fb2.png)

**Comment by Robinlovelace** [comment]
`shp2graph` is slow. The fastest approach I know of is with the `nabor` package, which I use in `stplanr`: https://github.com/ropensci/stplanr/blob/129b679c89a4ff9ba7f73dd5d59beb9bb734ace4/R/node-funs.R#L122

**Comment by luukvdmeer** [comment]
Ah, yes, I remember now we also used `nabor` in our blogpost. Regarding `shp2graph` I was mainly pointing to the figure with the explanation of the four strategies, which I like!

**Comment by Robinlovelace** [comment]
Yes it's a great figure, we need more good visuals like that. Good point.

**Comment by rafapereirabr** [comment]
Hi all. In the `gtfs2gps` package we use a quite fast function based on `C++` to [snap points to the closest points of another set using](https://github.com/ipeaGIT/gtfs2gps/blob/master/src/snap_points.cpp). Perhaps it might be useful here.

**Comment by luukvdmeer** [comment]
This topic was getting a little bit scattered.

There are now separate issues:

- Snapping points to the nearest node #57 
- Snapping points to the nearest point on the nearest edge #54 
- Snapping points to the network with pseudo-edges #58
