### ISSUE TITLE
Spatstat error in CRAN checks

### ISSUE THREAD

**Issue by luukvdmeer** [luukvdmeer/sfnetworks#265]
Got an email from CRAN about an error in the checks for sfnetworks. Seems to be related to the linnet integration. @agila5 could you take a look at this when you have time? We have until 2024-04-09 to fix it.

https://cran.r-project.org/web/checks/check_results_sfnetworks.html

**Comment by agila5** [comment]
Answers: 

1. I'm pretty sure that I correctly identified the error and I will prepare a PR in a few minutes
2. Apparently my assumptions were incorrect, meaning that R CMD check can still "access" the packages in the library even if they are not specified under Imports or Suggests

**Comment by agila5** [comment]
Hi @luukvdmeer. Friendly remainder that the deadline for the resubmission is 2024-04-09!

**Comment by luukvdmeer** [comment]
Yes, I am aware, I'm looking at it today, thanks!

**Comment by loreabad6** [comment]
Thank you for this! sfnetworks 0.6.4. is on CRAN 😄
