### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by SyedAImran** [luukvdmeer/sfnetworks#3]
Hi @luukvdmeer,
Thanks for writing this package. I had installed it and was using it for a project. I changed computers and when I tried to reinstall I cannot do it anymore. I am assuming an R update broke something here.
The error code is shown below. I would appreciate any help.
Syed 

* installing *source* package 'sfnetworks' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in findpack(package, lib.loc) : 
  there is no package called 'sfnetworks'
Calls: <Anonymous> -> findpack
Execution halted
ERROR: lazy loading failed for package 'sfnetworks'
* removing '\\DOMAIN/User$/UserID/documents/R/win-library/3.6/sfnetworks'
Error: Failed to install 'sfnetworks' from GitHub:
  (converted from warning) installation of package ‘C:/Users/UserID/AppData/Local/Temp/2/RtmpiAcKRV/file2d8c3de4708/sfnetworks_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by SyedAImran** [comment]
The one work around for this is by downloading the R files to a local directory and sourcing them for use in the project. That seems to fix the issue for now.

**Comment by luukvdmeer** [comment]
Hi! Sorry to miss out on this issue. The story of this package is that is was created as homework for an R course, and (at first) never meant to be really used afterwards. Therefore, maintenance and support have been very poor, sorry for that! I am happy to hear though that you found a solution.

After this blogpost (https://www.r-spatial.org/r/2019/09/26/spatial-networks.html), we might start to work actively on the package again in the near future!
