### ISSUE TITLE
Use st_boundary to get endpoints of lines

### ISSUE THREAD

**Issue by luukvdmeer** [luukvdmeer/sfnetworks#30]
When defining the endpoints of edges, sfnetworks now gets all coordinates of the LINESTRING, and then selects the first and last one. At the moment that was coded, I did not now that applying `st_boundary` on a LINESTRING already returns the two endpoints directly. The code would be cleaner and simpler when using st_boundary for finding the endpoints of an edge.

**Comment by luukvdmeer** [comment]
Today I learned the `lwgeom` package has the `st_startpoint` and `st_endpoint` functions. Might be worth to import it. Although I guess `st_boundary` of `sf` should give the same result? What do you think @Robinlovelace?

**Comment by Robinlovelace** [comment]
Yes, that's the way to go. In fact `st_endpoint()` exists because I nudged Edzer exactly for this purpose!

**Comment by luukvdmeer** [comment]
Interestingly I found out that using `st_boundary` is the fastest way of getting the endpoints of linestrings in the format that we want.

What I mean with that format is an object of class `sfc` with the boundary points of our linestrings ordered as follows (lets call this *format 1*):

- Startpoint line 1
- Endpoint line 1
- Startpoint line 2
- Endpoint line 2
- ...
- Startpoint line n
- Endpoint line n

As opposed to *format 2*:
- Startpoint line 1
- Startpoint line 2
- ...
- Startpoint line n
- Endpoint line 1
- Endpoint line 2
- ...
- Endpoint line n

We want format 1, because that means our first edge goes from node 1 to node 2, which is intuitive, instead of from node 1 to node n+1.

The following code produces exactly format 1:

```r
sf::st_cast(sf::st_boundary(sf::st_geometry(roxel)), "POINT")
```

While this produces format 2, and is a bit slower:

```r
c(lwgeom::st_startpoint(roxel), lwgeom::st_endpoint(roxel))
```

When we want the second one into format 1 we should do something like:

```r
do.call(
  "c",
  lapply(
    sf::st_geometry(roxel),
    function(x) c(lwgeom::st_startpoint(x), lwgeom::st_endpoint(x)
  )
)
```

Which is much slower because of the looping. Also it looses the crs information because you are looping over `sfg` objects.

Probably there are also other ways, but using the `st_boundary` approach turned out to be really fast and now reduces the constructing of an `sfnetwork` object from `roxel` to only about 60 milliseconds.
