### ISSUE TITLE
Setup testthat for package testing

### ISSUE THREAD

**Issue by loreabad6** [luukvdmeer/sfnetworks#32]

**Comment by luukvdmeer** [comment]
Basic tests are implemented. For a higher test coverage we should open new issues I think. The setup is done

**Comment by Robinlovelace** [comment]
Great to see we have tests!

Minor point: may be worth considering `tinytest` framework if you have any issues with failing tests. Context: https://github.com/r-spatial/sf/issues/1318#issuecomment-612074691

**Comment by luukvdmeer** [comment]
Looks interesting! I opened this as a new issue (with low priority for now)
