### ISSUE TITLE
Discussion of hackathon

### ISSUE THREAD

**Issue by Robinlovelace** [luukvdmeer/sfnetworks#35]
This is a place to discuss the hackathon in general, for anyone interested in what it will be and when (currently TBC we will provide updates when they come online). The original event cannot go ahead due to the Covid-19 pandemic.

Good news, we have re-scheduled the event. See https://www.eventbrite.co.uk/e/e-rum2020-satellite-event-hackathon-on-spatial-networks-tickets-90976873277 for details

![image](https://user-images.githubusercontent.com/1825120/80119937-3e8ea580-8582-11ea-86bb-faf8c9d12b0a.png)

**Comment by Robinlovelace** [comment]
Discussing this today, we will post a an agenda soon.

**Comment by luukvdmeer** [comment]
I think we can say it was a success! The individual hackathon issues I will leave open as a place to share code snippets, other findings, or discuss further!
