### ISSUE TITLE
Consider tinytest as alternative for unit testing

### ISSUE THREAD

**Issue by luukvdmeer** [luukvdmeer/sfnetworks#39]
As @Robinlovelace mentioned, this might be worth looking at as alternative for `testthat`, if the latter causes problems.

See: https://github.com/markvanderloo/tinytest

**Comment by loreabad6** [comment]
So far, there have not been any problems using `testthat`. We only use a CRS check to test edges and nodes are both under the same CRS and are both transformed. Reading the thread mentioned in #32 I have the feeling it will not affect us. But of course feel free to re-open if there is any problem in the future :)
