### ISSUE TITLE
Fine-tune continuous integration with GH actions

### ISSUE THREAD

**Issue by luukvdmeer** [luukvdmeer/sfnetworks#43]
GH actions seems to work good now, but we should still fine-tune it to make it better.

#### Consider Linux as OS for pkgdown deployment
Right now [pkgdown.yaml](https://github.com/luukvdmeer/sfnetworks/blob/master/.github/workflows/pkgdown.yaml) runs on macOS latest. For the similar [R-CMD-Check.yaml](https://github.com/luukvdmeer/sfnetworks/blob/master/.github/workflows/R-CMD-check.yaml) (which does both macOS and Linux), the Linux check finishes twice as fast as the macOS one. It might be worth considering to run the pkgdown deployment on a Linux VE instead?

(Not sure if this will cause other errors, but let's see. Deploying pkgdown with GH actions is still a very new thing that seems to be not so often used yet. Most use Travis.)

#### Check if it is possible to prevent installing dependencies twice
Right now, both [pkgdown.yaml](https://github.com/luukvdmeer/sfnetworks/blob/master/.github/workflows/pkgdown.yaml) and [R-CMD-check.yaml](https://github.com/luukvdmeer/sfnetworks/blob/master/.github/workflows/R-CMD-check.yaml) install all system dependencies (gdal and friends) and all R package dependencies, before doing the core of their job (deploying pkgdown and running an R CMD check, respectively). The difference is that `pkgdown.yaml` runs only at pushes to master, and `R-CMD-check.yaml` at pushes to master, pushes to develop and pull requests. That makes sense. However, it also means that when pushing to master, the whole dependency installation, which takes up to almost half an hour, happens twice. Maybe we can explore if this double work can somehow be prevented.

#### Use new pkgdown release
Right now we use the `deploy_local()` internal function of `pkgdown` in combination with a GitHub Personal Access Token and GitHub Secret to deploy the pkgdown website at every push to master. See [here](https://github.com/maxheld83/ghpages#secrets) why this is needed. Although in [this issue](https://github.com/r-lib/actions/issues/28) of pkgdown it is stated that this complicated way should not be needed anymore, I could not get it to work without.

As I understand, we should now be able to use the `deploy_to_branch()` function of `pkgdown`, which is there since version 1.5. However, it did not work for me yet., for the same reasons as described [here](https://github.com/r-lib/pkgdown/issues/1275). That issue is solved for Travis, but with GH actions it still occurred (at least in my situation). According to what @Nowosad said [here](https://github.com/geocompr/geocompkg/issues/10), it is better to wait for the new CRAN-release of pkgdown?

Things work good as we have it now, but when the new pkgdown is released on CRAN, it might be worth considering to update the `pkgdown.yaml` file and make the process cleaner and simpler.

#### Regularly update sf related GH actions
As said [here](https://github.com/luukvdmeer/sfnetworks/pull/34), GH actions for sf is still actively developed and evolving rapidly. We should regularly update the yaml files to keep up with the most recent versions.

Relates to #2

**Comment by luukvdmeer** [comment]
That could also allow us to locally run GH actions before pushing (which is especially helpful when changing the yaml files and wanting to check if those changes work)

See https://github.com/nektos/act

**Comment by Robinlovelace** [comment]
Definitely a good plan, I switched the deploy to Linux on projects and it worked fine.

**Comment by luukvdmeer** [comment]
I added some extra GH actions remarks that we need to look at. No high priority, since for now everything works as it is. But improving is always good ;)

**Comment by luukvdmeer** [comment]
GH actions workflows are update according to the newest templates of the actions package. They all use Ubuntu now. `secrets.GITHUB_TOKEN` instead of a personal token to improve security. Also, a test coverage workflow is added. All works good and is much cleaner now.
