### ISSUE TITLE
Fine-tune pkgdown website

### ISSUE THREAD

**Issue by loreabad6** [luukvdmeer/sfnetworks#44]
- [x] **Group functions on reference tab**
Group and describe `sfnetworks` functions accordingly. Reference [here](https://pkgdown.r-lib.org/articles/pkgdown.html#reference-1).

- [x] **Check auto-linking to documentation**
Although `pkgdown` does this automatically, some links might not be working properly. Reference [here](https://pkgdown.r-lib.org/articles/linking.html).

- [x] **Add news tab and changelog**
Add news tab to specify new features for each release. Reference [here](https://pkgdown.r-lib.org/articles/pkgdown.html#news-1).

**Comment by luukvdmeer** [comment]
@loreabad6 Can you take a look at the only unchecked box that is left? Then we can close this before the end of milestone 2.

**Comment by loreabad6** [comment]
Seems to me like the linking is good. I added an internal link now to the vignettes, but I cannot test if it works until it is deployed. I also seemed to have corrected the order of the vignettes on the dropdown menu of "Articles". Let's keep this open until we merge the changes to master and really check the results!

**Comment by luukvdmeer** [comment]
Merged to master
