### ISSUE TITLE
Add examples to function documentations

### ISSUE THREAD

**Issue by loreabad6** [luukvdmeer/sfnetworks#45]
Include examples for the `sfnetworks` functions.

**Comment by loreabad6** [comment]
Progress:

- [ ] attrs.R 
- [ ] blend.R 
- [ ] edge_measures.R 
- [ ] join.R 
- [x] morphers.R 
- [ ] nearest.R 
- [x] plot.R 
- [ ] sf.R 
- [x] sfnetwork.R 
- [x] shortest_paths.R 
- [ ] tibble.R 
- [ ] tidygraph.R

**Comment by Robinlovelace** [comment]
This is a great summary of what needs doing here.

**Comment by luukvdmeer** [comment]
Lots, lots and lots of examples added to many different functions. Thanks @loreabad6
