### ISSUE TITLE
Multi-modal routing with dodgr and gtfsrouter

### ISSUE THREAD

**Issue by mpadge** [luukvdmeer/sfnetworks#48]
The hackathon description claims that,

> no mature, well tested and ‘tidy’ class exists for spatial network data.

The `sfnetworks` package represents just one approach to this issue. An alternative representation is provided by the package [`dodgr`](https://github.com/atfutures/dodgr), which stands for "Distances on Directed GRaphs". [`dodgr`](https://github.com/atfutures/dodgr) represents networks as single rectangular `data.frame`s in which each row is an edge. The package demands that each vertex be given a unique identifier, enabling for example the representation of overpasses in which two edges may cross at geometrically identical points yet may not intersect. This insistence that each vertex have a unique identifier makes the transition to a point-based representation (analogous to the [`tidygraph`](https://github.com/thomasp85/tidygraph) approach of activating vertices) entirely trivial, enabling a single, coherent edge-based representation to be used at all times.

Not only is [`dodgr`](https://github.com/atfutures/dodgr) designed to represent and process directed graphs, it also represents *dual-weighted* graphs, in which each edge has two weights. Dual-weighted representations are essential for realistic routing through street networks, because the geometrically shortest path will often not be the best. Paths generally taken through street networks depend on preferences which differ for different modes of transport. Dual weighted routing systems calculate paths based on one set of weights reflective of typical preferences for a given mode of transport, while resultant distances are calculated using a different set of edge properties (for example direct geometric distances).

[`dodgr`](https://github.com/atfutures/dodgr) is primarily intended to perform ["heavy lifting"](https://github.com/sa-lee/rwalkable) tasks typically necessary to understand city-scale transport problems. The package can also calculate *fastest* rather than *shortest* paths. The resultant routing times reflect realistic temporal effects such as waiting times at traffic lights, for turning across oncoming traffic, and - for pedestrians and cyclists - the effects of incline. The ability to perform realistic routing is a pre-requisite for *multi-modal* routing, an ability currently only available in R through accessing an external service via the [`opentripplanner` package](https://github.com/ropensci/opentripplanner).

A great hackathon task would be to combine the routing abilities of [`dodgr`](https://github.com/atfutures/dodgr) with the public transport routing offered by the [`gtfsrouter` package](https://github.com/atfutures/gtfs-router) to generate multi-modal routing between any two chosen points. It would be particularly useful to analyse how one might get between pairs of points by foot, on a bicycle, or combining either of these modes with public transport, comparing both times and distances.

**Comment by luukvdmeer** [comment]
Very interesting topic!

**Comment by surgissant** [comment]
This would be really useful for my work, it's exactly what I've been using R for recently in transport planning for Melbourne, Australia.
https://www.meetup.com/MelbURN-Melbourne-Users-of-R-Network/events/268793495/

**Comment by mpadge** [comment]
```{r}
library(dodgr)
library (osmdata)
library(gtfsrouter)

# get berlin street network and weight it for pedestrian transport:
net <- dodgr_streetnet_sc ("berlin germany", quiet = FALSE)
x <- weight_streetnet (net, wt_profile = "foot")

# load locally-downloaded version of VBB GTFS for berlin:
gtfs <- extract_gtfs ("vbb.zip")
gtfs <- gtfs_timetable (gtfs)

# reduce street network down to junctions only (makes routing much more efficient):
x <- x [x$component == 1, ]
xc <- dodgr_contract_graph (x)

# select two random vertices (nodes) from the network to use as routing points:
v <- dodgr_vertices (xc)
from <- sample (v$id, 1)
to <- sample (v$id, 1)
from_xy <- v [v$id == from, ]
to_xy <- v [v$id == to, ]

# walking time between those points:
twalk <- dodgr_times (xc, from = from, to = to)
as.numeric (twalk) / 3600

# convert points to nearest stops in GTFS feeds:
library (geodist)
from_d <- geodist (from_xy, gtfs$stops)
from_stop <- gtfs$stops$stop_name [which.min (from_d)]
to_d <- geodist (to_xy, gtfs$stops)
to_stop <- gtfs$stops$stop_name [which.min (to_d)]

# use gtfsrouter to get route between from_stop and to_stop
# (this will commonly fail; will be fixed in gtfs-router/issues#26)
r <- gtfs_route (gtfs, from = from_stop, to = to_stop)
t0 <- tail (hms (r$arrival_time), 1) - hms (r$departure_time [1])
# t0 is time in seconds for GTFS trip

# finally, add walking times to and from the start and end stops:
from_stop <- gtfs$stops [which.min (from_d), ]
from_stop <- c (from_stop$stop_lon, from_stop$stop_lat)
to_stop <- gtfs$stops [which.min (to_d), ]
to_stop <- c (to_stop$stop_lon, to_stop$stop_lat)

t1 <- dodgr_times (xc, from = from_xy, to = from_stop)
t2 <- dodgr_times (xc, from = to_xy, to = to_stop)

# total time using public transport:
vbbtime <- t1 + as.numeric (seconds (t0)) + t2
```

**Comment by mpadge** [comment]
To be developed in [`ATFutures/m4ra`](https://github.com/ATFutures/m4ra). @luukvdmeer I guess issue can be closed now, right? The hackathon was very productive, and this issue will lead directly to a new package. Thanks for all the work, and the inspiration to do this!

**Comment by luukvdmeer** [comment]
Great to see it resulting in a new package! I will close the issue here and watch the new repository
