### ISSUE TITLE
Function to calculate the circuity of an edge

### ISSUE THREAD

**Issue by luukvdmeer** [luukvdmeer/sfnetworks#51]
**Is your feature request related to a problem? Please describe.**
There are graph measures so specific to spatial networks, that neither `sf`, neither `tidygraph` has functions to calculate them. One such measure is the *circuity* of an edge, as described in [this paper](https://journals.sagepub.com/doi/10.1068/b130131p):

> Circuity, the ratio of network to Euclidean distances, describes the directness of trips and the efficiency of transportation networks.

**Describe the solution you'd like**
An edge measurement function, in the same style as tidygraphs "edge measures" group of functions, that calculates the circuity of a spatially explicit edge: `edge_circuity`.

**Comment by luukvdmeer** [comment]
This is implemented in the new version, along with other edge measures

**Comment by idshklein** [comment]
Suggestion: adding a parameter for self loop edges, in order to return NA instead of inf

**Comment by luukvdmeer** [comment]
Out of interest: when are you running into problems with `Inf` values?

**Comment by idshklein** [comment]
When I try to calculate mean neighborhood circuitry

**Comment by luukvdmeer** [comment]
Makes sense. I added the `Inf_as_NaN` value to return `NaN` instead of `Inf`. `NaN` is also returned when for some reason the edge length is 0. Then mean calculations (and others) can be run with `na.rm  = TRUE`. I think it makes sense to even use the default of `Inf_as_NaN = TRUE`.
