### ISSUE TITLE
Visualization of sfnetwork objects

### ISSUE THREAD

**Issue by Robinlovelace** [luukvdmeer/sfnetworks#7]
The visualisation of the geographic components of `sfnetwork` objects is taken care of by `sf` and mapping packages such as `leaflet`, `mapview`, `tmap` and `mapview` and the graph component can be plotted by the `igraph` package. Worth considering other ways of visualising graphs? Just saw this and played with the interactive examples on the website and thought it may be of interest: https://github.com/JohnCoene/sigmajs

**Comment by luukvdmeer** [comment]
@agila5 Just a thought I got: You mentioned once you were planning to look into `ggplot2` visualizations of `sfnetworks`. Maybe it is also an idea to look into `ggraph`, which already works flawlessly in combination with `tidygraph` objects. It should the just be able to recognize the geometry list column and plot nodes and/or edges with `geom_sf`.

See https://ggraph.data-imaginist.com/

**Comment by loreabad6** [comment]
I created a repo here: https://github.com/sfnetworks/sfnetworks_viz for our wirk this afternoon. Feel free to add ideas, code, data or anything that pops to mind!

**Comment by Robinlovelace** [comment]
Follow-on from my comment, it would be interesting to use the `tranformer` package to shift between the geographic and 'graph space' representations - seems to work with sf objects already: https://github.com/thomasp85/transformr

**Comment by luukvdmeer** [comment]
Since the hackathon is now behind us, I will close the hackathon issues. But I look forward to new specific feature request issues that resulted from the hackathon!

(although for this specific topic most issues/PRs will be probably be directed to `ggraph`)
