### ISSUE TITLE
Update introductory vignette

### ISSUE THREAD

**Issue by Robinlovelace** [luukvdmeer/sfnetworks#8]
Typically to be called pkgname.Rmd for `pkgdown`, `sfnetworks.Rmd` in this case.

**Comment by Robinlovelace** [comment]
I see it's already been created: https://github.com/luukvdmeer/sfnetworks/blob/master/vignettes/sfnetworks.Rmd

Great work @luukvdmeer

**Comment by luukvdmeer** [comment]
Just as a reminder for myself: this is of high priority to wrap up milestone 1. The vignette should include:

- [ ] Guidelines on installation
- [ ] General philosophy/goal of the package
- [ ] Explanation of the sfnetwork class
- [ ] Guidelines on how to create an sfnetwork object
- [ ] Overview of the sf methods for sfnetwork objects (summary of https://github.com/luukvdmeer/sfnetworks/issues/18#issuecomment-607896317)
- [ ] Some simple examples that use both sf and tidygraph functions
- [ ] Overview of what is still to come

**Comment by luukvdmeer** [comment]
Introductory vignette is added: https://github.com/luukvdmeer/sfnetworks/blob/master/vignettes/intro.Rmd
