### ISSUE TITLE
Vignette reorganization

### ISSUE THREAD

**Issue by loreabad6** [luukvdmeer/sfnetworks#92]
Proposed reorganization of vignettes:

1. Overview vignette
        - Summary of all the features and link to the other vignettes 
2. Data structure 
       - How it works (subclasses) and what tidyverse methods are supported 
       - How to construct the network 
3. Join and filter spatially 
4. Routing 
       - Spatial shortest paths 
       - Snapping 
5. Spatial measures 
        - Nodes and edges 
6. Spatial morphers 
7. Known issues 
8. Pre-processing

**Comment by luukvdmeer** [comment]
We now have 5 vignettes covering most use-cases:

- [The sfnetwork data structure](https://luukvdmeer.github.io/sfnetworks/articles/structure.html)
- [Network pre-processing and cleaning](https://luukvdmeer.github.io/sfnetworks/articles/preprocess_and_clean.html)
- [Spatial joins and filters](https://luukvdmeer.github.io/sfnetworks/articles/join_filter.html)
- [Routing](https://luukvdmeer.github.io/sfnetworks/articles/routing.html)
- [Spatial morphers](https://luukvdmeer.github.io/sfnetworks/articles/morphers.html)
